
pipeline:
  hugo:
    image: cbrgm/drone-hugo:latest
    validate: true
    when:
      event: push

  rebuild-cache:
    image: drillster/drone-volume-cache
    rebuild: true
    volumes:
      - website_static_files:/output