title = "Serious Shit"
baseURL = "http://v22017125338957481.megasrv.de:8080/"
tags = ["portfolio", "web design", "blog"]
languageCode = "en-US"
config = "config.toml"
theme = "serious"
canonifyURLS = true
googleAnalytics = ""
disqusShortname = ""
disableKinds = ["taxonomy", "taxonomyTerm"] # This theme does not currently use "tag" and "category" taxonomies


[Params]
    tagline = "because i love this shit"
    author = "Hagen Hasenbalg"
    copyright = "Hagen Hasenbalg"
    favicon = "favicon.ico"

    twitter = ""
    linkedin = ""
    github = "SeriousShit"
    xing = "Hagen_Hasenbalg"

    email = "h.hasenbalg@me.com"
    googleTagManger = ""
    highlightJS = true
    credit = true
    customCSS = false
    cacheBustCSS = false
    cacheBustJS = false
    dateform = "02.01.2006"

[[menu.main]]
    name = "Portflolio"
    url  = "/#portfolio"
    weight = 1
[[menu.main]]
    name = "About"
    url  = "/#about"
    weight = 2
[[menu.main]]
    name = "Blog"
    url  = "/#blog"
    weight = 3
[[menu.main]]
    name = "Contact"
    url  = "/#contact"
    weight = 4
