title = "Hagen Hasenbalg"
baseURL = "/"
tags = ["portfolio", "web design", "blog"]
config = "config.toml"
theme = "serious"
disqusShortname = ""

defaultContentLanguage = "en"

[languages.en]
weight = 0
languageName = "English"

[[languages.en.menu.main]]
    url    = "/"
    name   = "Home"
    weight = 5
[[languages.en.menu.main]]
    name = "portfolio"
    url  = "/#portfolio"
    weight = 1
[[languages.en.menu.main]]
    name = "about"
    url  = "/#about"
    weight = 2
[[languages.en.menu.main]]
    name = "blog"
    url  = "/#blog"
    weight = 3
[[languages.en.menu.main]]
    name = "contact"
    url  = "/#contact"
    weight = 4


[languages.de]
weight = 10
languageName = "Deutsch"

[[languages.de.menu.main]]
    url    = "/"
    name   = "Home"
    weight = 5
[[languages.de.menu.main]]
    name = "portfolio"
    url  = "/#portfolio"
    weight = 1
[[languages.de.menu.main]]
    name = "about"
    url  = "/#about"
    weight = 2
[[languages.de.menu.main]]
    name = "blog"
    url  = "/#blog"
    weight = 3
[[languages.de.menu.main]]
    name = "contact"
    url  = "/#contact"
    weight = 4



[Params]
    tagline = "because i love this shit"
    author = "Hagen Hasenbalg"
    copyright = "Hagen Hasenbalg"
    favicon = "favicon.ico"

    twitter = ""
    linkedin = ""
    github = "SeriousShit"
    xing = "Hagen_Hasenbalg"

    email = "h.hasenbalg@me.com"
    googleTagManger = ""
    highlightJS = true
    credit = true
    customCSS = false
    cacheBustCSS = false
    cacheBustJS = false
    dateform = "02.01.2006"



