title = "Serious Shit"
baseURL = "hagen-hasenbalg.de"
tags = ["portfolio", "web design", "blog"]
languageCode = "en-US"
config = "config.toml"
theme = "serious"
disqusShortname = ""

[languages]
[languages.en]
weight = 1

[languages.de]
weight = 2


[Params]
    tagline = "because i love this shit"
    author = "Hagen Hasenbalg"
    copyright = "Hagen Hasenbalg"
    favicon = "favicon.ico"

    twitter = ""
    linkedin = ""
    github = "SeriousShit"
    xing = "Hagen_Hasenbalg"

    email = "h.hasenbalg@me.com"
    googleTagManger = ""
    highlightJS = true
    credit = true
    customCSS = false
    cacheBustCSS = false
    cacheBustJS = false
    dateform = "02.01.2006"

[[menu.main]]
    name = "portfolio"
    url  = "/#portfolio"
    weight = 1
[[menu.main]]
    name = "about"
    url  = "/#about"
    weight = 2
[[menu.main]]
    name = "blog"
    url  = "/#blog"
    weight = 3
[[menu.main]]
    name = "contact"
    url  = "/#contact"
    weight = 4

